/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inheritances;

import java.util.Date;

/**
 *
 * @author hp
 */
public class Circle extends Geometric{
    private double radius;

    //default constructure -no agrument generated by compliler
    public Circle() { //default constructure -no agrument generated by programmer
                      //auto default disappear
        //super(); unseen call Geometric() in superclass
    }

    public Circle(double radius) {
        this.radius = radius;
    }

    public Circle(double radius, String Color, Date dateCreated) {
        super(Color, dateCreated); // call superclass's construct cannot call by name must use keyword "super"
                                   // therefore call superclass at first statement
        this.radius = radius;
    }

    @Override
    public String toString() {
        return "datecreated: "+super.getDateCreated()+"color: "+super.getColor()+"Circle{" + "radius=" + radius + '}';
    }

    
    
}
